### Récupération de tous les levels
GET http://localhost:3000/api/levels

### Récupération d'un level id
GET http://localhost:3000/api/levels/3

### Création d'un level
POST http://localhost:3000/api/levels
Content-Type: application/json

{
    "name": "hardcore ++"
}

### Modification d'un level
PATCH http://localhost:3000/api/levels/7
Content-Type: application/json

{
    "name": "hardcore +"
}

### Suppression d'un level
DELETE http://localhost:3000/api/levels/10